
export interface AutoRequest {
    transactionDateTimeLdt:   string;
    gmtTicketTimeLimitZdt:    null;
    pnr:                      Pnr;
    pnrNames:                 PnrName[];
    pnrFqtvs:                 PnrFqtv[];
    transactionDateTime:      number;
    gmtTicketTimeLimit:       null;
    gmtTicketTimeLimitZdtStr: null;
}

export interface Pnr {
    createDateTime:              number;
    createDateTimeLdt:           string;
    locator:                     string;
    purgeDate:                   number;
    purgeDateLd:                 string;
    infant:                      boolean;
    parentPnr:                   boolean;
    childPnr:                    boolean;
    ticketStatus:                string;
    codeShare:                   boolean;
    blockSpaceRemark:            boolean;
    currentHistorySeq:           number;
    primaryNameType:             string;
    groupType:                   string;
    plt:                         boolean;
    primaryName:                 string;
    pnrSeqNumber:                number;
    aaaCityCode:                 string;
    homeStationCityCode:         string;
    createDutyCode:              string;
    createAgentSine:             string;
    createPLTOfficeDesignator:   null;
    createCRSCode:               null;
    creationCountryCode:         string;
    agencyOwner:                 null;
    numberInParty:               number;
    numberOfInfants:             number;
    numberInNames:               number;
    origNumberInNames:           number;
    aadvantageCount:             number;
    executivePlatinumCount:      number;
    platinumCount:               number;
    vipCount:                    number;
    seniorCitizenCount:          number;
    seniorCitizenCompanionCount: number;
    goldCount:                   number;
    platinumProCount:            number;
    conciergeKeyCount:           number;
    airPassCount:                number;
    immediateParentLocator:      null;
    divideDateTime:              null;
    divideDateTimeLdt:           null;
    ticketInfo:                  string;
    contractNumber:              null;
    receivedDateTime:            number;
    receivedDateTimeLdt:         string;
    lastUpdateDateTime:          number;
    lastUpdateDateTimeLdt:       null;
    origBkgCRSCode:              null;
    origBkgAgencyIATANumber:     string;
    origBkgAgencyCityCode:       string;
    origBkgCountryCode:          string;
    origBkgDutyCode:             string;
    historyTruncated:            boolean;
    historyCorrupted:            boolean;
    earliestPOSData:             null;
    earliestBSGPOSData:          null;
    segments:                    SegmentElement[];
    historyResetDate:            null;
    historyResetDateLdt:         null;
    rlocText:                    null;
    rlocCRSCityCode:             null;
    rlocCRSCode:                 null;
    rlocOAPnrLocator:            null;
    rlocAgencyIdCode:            null;
    rlocAgencyIATANumber:        null;
    rlocAgencyCityCode:          null;
    origParentLocator:           null;
    pointOfOriginCityCode:       string;
    nonRev:                      boolean;
    positiveSpace:               boolean;
    awardBooking:                boolean;
    govtFare:                    boolean;
    extraSeat:                   boolean;
    cabinBaggage:                boolean;
    airpass:                     boolean;
    airpassType:                 null;
    fqtuSSR:                     boolean;
    itinActiveInd:               boolean;
    vcrInd:                      boolean;
    rmEstimateInd:               boolean;
    umnrSSR:                     boolean;
    petSSR:                      boolean;
    autoReqOptOut:               boolean;
}

export interface SegmentElement {
    segment:                    SegmentSegment;
    fareClass:                  string;
    segSequence:                number;
    statusCode:                 string;
    origStatusCode:             string;
    cabinCode:                  string;
    active:                     boolean;
    inbound:                    boolean;
    outbound:                   boolean;
    sabreNumberInParty:         number;
    origNumberInParty:          number;
    prevStatusCode:             string;
    roundRobinCity:             boolean;
    bsgLocator:                 null;
    bookingDateTime:            number;
    bookingDateTimeLdt:         string;
    historyTransactionTime:     null | string;
    createDateTime:             number;
    createDateTimeLdt:          string;
    cancelDateTime:             null;
    cancelDateTimeLdt:          null;
    codeShare:                  boolean;
    crsCode:                    null;
    agencyIATANumber:           string;
    agencyCityCode:             string;
    countryCode:                string;
    dutyCode:                   string;
    marketingAirline:           string;
    operatingAirline:           string;
    marketingClass:             string;
    operatingClass:             string;
    marketingFlightNbr:         number;
    operatingFlightNbr:         number;
    klDateTime:                 null;
    klDateTimeLdt:              null;
    obDateTime:                 null;
    obDateTimeLdt:              null;
    lastUpdate:                 number;
    lastUpdateLdt:              string;
    departureDateTime:          number;
    departureDateTimeLdt:       string;
    arrivalDateTime:            number;
    arrivalDateTimeLdt:         string;
    bkgAAACityCode:             null | string;
    bkgHomeStaCityCode:         null | string;
    bkgDutyCode:                null | string;
    bkgAgentSine:               null | string;
    bkgPltOfficeDesignator:     null;
    bkgCrsCode:                 null;
    currentAAACityCode:         null | string;
    currentHomeStaCityCode:     null | string;
    currentAgentSine:           null | string;
    currentDutyCode:            null | string;
    currentPltOfficeDesignator: null;
    currentCrsCode:             null;
    cancelAAACityCode:          null;
    cancelHomeStaCityCode:      null;
    cancelAgentSine:            null;
    cancelDutyCode:             null;
    cancelPltOfficeDesignator:  null;
    cancelCrsCode:              null;
    bkgReceivedFrom:            null | string;
    currentReceivedFrom:        null | string;
    cancelReceivedFrom:         null;
    copiedFromParent:           boolean;
    departureDateTimeGMT:       number;
    departureDateTimeGMTZdt:    string;
    arrivalDateTimeGMT:         number;
    arrivalDateTimeGMTZdt:      string;
    marriedSegment:             boolean;
    fqtuSSR:                    boolean;
    irssSSR:                    boolean;
    tripDepartureDate:          number | null;
    tripDepartureDateLd:        null | string;
    tripBoard:                  null | string;
    tripOff:                    null | string;
    inline:                     boolean;
    online:                     boolean;
    offline:                    boolean;
    uniqueId:                   string;
    originalFare:               string;
    effectiveBidPrice:          string;
    adjustedFare:               string;
    adjustedBidPrice:           string;
    footprintFareClass:         string;
    lowestAvailFareClass:       string;
    pointOfCommencement:        string;
    customerScore:              number;
    additionalFlag:             string;
    additionalData:             string;
    tierLevel:                  number;
    supplierCode:               string;
    marketTypeOrigin:           string;
    marketTypeOriginLevel:      number;
    marketTypeDestination:      string;
    marketTypeDestinationLevel: number;
    tripMarketOrigin:           string;
    tripMarketOriginLevel:      number;
    tripMarketDestination:      string;
    tripMarketDestinationLevel: number;
    fareMarketOrigin:           string;
    fareMarketOriginLevel:      number;
    fareMarketDestination:      string;
    fareMarketDestinationLevel: number;
    regularFareType:            boolean;
    sponsorFareType:            boolean;
    defaultFareType:            boolean;
    sponsorDefault:             boolean;
    hostDefault:                boolean;
    defaultEvaluationType:      boolean;
    sumOfLocals:                boolean;
    trueOD:                     boolean;
    longestSegmentFare:         boolean;
    dominantSegmentFare:        boolean;
    local:                      boolean;
    financial:                  boolean;
    physical:                   boolean;
    forcedSell:                 boolean;
    schedChg:                   boolean;
    forcedPartialCancel:        boolean;
    ttyRejectAgent:             boolean;
    ttyTransaction:             boolean;
}

export interface SegmentSegment {
    airline:              string;
    flightNumber:         number;
    origin:               string;
    destination:          string;
    departureDate:        number;
    departureDateLd:      string;
    rowCreateDateTime:    null;
    rowCreateDateTimeLdt: null;
    boardCountryCode:     string;
    offCountryCode:       string;
}

export interface PnrFqtv {
    cip:                    boolean;
    departureDateLdt:       null;
    eliteQualifyingDollars: number;
    aairpass:               boolean;
    fqtvNumber:             string;
    prevActionCode:         string;
    currActionCode:         string;
    receivingCarrierCode:   string;
    owningCarrierCode:      string;
    vitType:                null | string;
    freeTextInfo:           null;
    textNameData:           null;
    boardPoint:             null;
    offPoint:               null;
    flightNumber:           null;
    serviceClass:           string;
    historyAction:          null;
    nameID:                 number;
    cancelRebookAction:     boolean;
    airlineClubMember:      boolean;
    wvitType:               number;
    aaaModifiedItem:        boolean;
    dxaIndirectCancel:      boolean;
    haOwnedFreqTravNumber:  boolean;
    newItemThisTransaction: boolean;
    ddate:                  null;
}

export interface PnrName {
    historyAction: null;
    lastName:      string;
    firstName:     string;
    groupName:     null;
    refNum:        string;
    title:         null;
    suffix:        null;
    nameId:        number;
    nameType:      string;
    ageClass:      string;
    seatCount:     number;
}
